### ISSUE TITLE
ЛР1 - Примеры тестов для веб-приложения "Silver Screen"

### ISSUE THREAD

**Issue by VladislavIlyuschits** [VladislavIlyuschits/software-testing#1]
### Веб-приложение: 
В качестве тестируемого веб-приложения была выбрана платформа для покупки билетов в кино [silverscreen.by](https://silverscreen.by).
### Примеры тестов: 

1. **Смоук-тест:**
Покупка билета на любой сеанс кино на свободное время и место с помощью банковской карты. Убедиться, что билет пришел на почту, платеж совершен.

2. **Критического пути**:
Зарегистрироваться, войти в систему и купить билет на любой сеанс кино на свободное время и место с помощью банковской карты. Убедиться, что билет пришел на почту, платеж совершен

3. **Расширенное:**
Зарегистрироваться, войти в систему и купить 2 билета на любой сеанс кино на текущий день+1, свободное время и места, ввести промокод и оплатить с помощью банковской карты. Убедиться, что 2 билета пришли на почту, платежи совершены

4. **Позитивное:**
Зарегистрироваться на сайте и убедиться, что письмо об успешной регистрации пришло на почту

5. **Негативное:**
Зарегистрироваться с e-mail без знака "@" и убедиться, что регистрация не прошла и появилось уведомление о неправильном e-mail

6. **Метод чёрного ящика:**
Подписаться на новости и убедиться, что приветственное письмо пришло на почту

7. **Метод серого ящика:**
При подписке на новости указать e-mail без ".", убедиться, что появляется уведомление о неправильном e-mail

8. **Метод белого ящика:**
Подписаться на новости и убедиться, что появилась запись с новым e-mail в базе данных и приветственное письмо отправлено

9. **Графического интерфейса:**
При выборе места в зале навести курсор на места разного цвета и убедиться, что занятые места имеют другой цвет и при наведении появляется всплывающая подсказка о том, что место недоступно

10. **Удобства использования:**
Перейти с главной страницы на форму входа на сайт

11. **Локализации:** 
Сайт предоставлен на 1 языке для Беларуси. 
Тестирование локализации представляет собой набор проверок, проверяющий адаптированность сайта для аудитории, имеющей различные языковые и культурные особенности

12. **Интернационализации:**
Интернационализация также не предусмотрена на сайте.
Тестирование интернационализации предполагает проверки,связанные с процессами упрощение локализации, то есть кодировок, расположения текста в зависимости от культурных особенностей и загрузки локализированных элементов

13. **Совместимости:**
Авторизованный пользователь совершает покупку билетов, убедиться, что билеты появились в его личном кабинете

14. **Динамическое:**
Ввести пароль отличный от подтверждения пароля и попытаться зарегистрироваться

15. **Статическое:** 
Статическое тестирование - это тестирование без запуска кода на исполнение, то есть тестирование требований или анализ программного кода

16. **Инсталляционное:**
Инсталляционное тестирование - проверка работы ПО в искусственно созданной среде с целью проверки работоспособности в различных системах

17. **Производительности:**
Авторизоваться в разные аккаунты одновременно

18. **Безопасности:**
Попытаться через SQL-инъекцию войти на сайт, введя ее в поле логина формы входа и используя имя зарегистрированного пользователя

19. **В зависимости от природы приложений (мобильное, веб, настольное)** 
Войти в систему и нажать кнопку выхода, убедиться, что сессия авторизованного пользователя завершена

**Comment by vliplianina** [comment]
п.13 больше подходит для проверки интеграции между модулями. 
В рамках совместимости (compatibility) проверяется совместимость версий приложений / баз данных и/или платформ/браузеров.
Принято.
