### ISSUE TITLE
ЛР2 - Тестирование требований "Оповещения для клиента"

### ISSUE THREAD

**Issue by VladislavIlyuschits** [VladislavIlyuschits/software-testing#2]
**1. Оповещения - Уточнить количество адресов для отправки сообщения.**
В спецификации требований "Оповещения для клиента" не описано количество и возможность выбора нескольких адресов для доставки сообщения. Требуется уточнение.

**2. Оповещения - Дополнить системы коммуникаций для доставки SMS-сообщений.**
В спецификации требований "Оповещения для клиента" не описан полный список систем коммуникаций для доставки сообщения. Требуется уточнение.

**3. Оповещения - Уточнить пути появления Push-уведомлений.**
В спецификации требований "Оповещения для клиента" не описаны конкретные пути отправки Push-уведомлений. Требуется уточнение.

**4. Оповещения - Уточнить обстоятельства для отправки через любой сервис оповещений.**
В спецификации требований "Оповещения для клиента" не описаны условия для отправки каждого из сервиса уведомлений: Email, SMS или Push. То есть могут ли оповещения быть отправлены через все сервисы или через 1 конкретный. Требуется уточнение.

**5. Оповещения - Уточнить, является ли требование о доставке SMS-сообщений через другие системы коммуникаций обязательным.**
В спецификации требований "Оповещения для клиента" не указана обязательность выполнения требования о доставке SMS-сообщений через другие системы коммуникаций

**Comment by vliplianina** [comment]
Принято
