### ISSUE TITLE
ЛР3 - Тест-анализ и тест-дизайн поля ввода даты "с" и "по"

### ISSUE THREAD

**Issue by VladislavIlyuschits** [VladislavIlyuschits/software-testing#3]
[Лабораторная работа 3](https://github.com/VladislavIlyuschits/software-testing/files/4641033/lab3.xlsx)

**Comment by vliplianina** [comment]
Недостаточно как позитивных, так и негативных тестов.
При проектировании позитивных тестов рекомендую отдельно проверять поля "с" и "по" на граничные значения, иначе в рамках одного теста проверяется сразу 3 условия: граничное значение "с", граничное значение "по" и минимально допустимый диапазон. В случае, если минимально допустимый диапазон задан неверно, большая часть тестов будет невалидна.

**Comment by VladislavIlyuschits** [comment]
Вариант 2.

Поля ввода даты "с" и "по":

применяется маска ДД.ММ.ГГГГ
допустимый диапазон [01.01.1900;31.12.2090]
значение поля "с" не должно превышать значение поля "по"
Кнопка "Сохранить". Действие по нажатию:

при допустимом значении полей ввода дат: уведомление «Сохранено»
при недопустимом значении полей ввода дат: уведомление «Ошибка»

Соообщение "Сохранено" при следующих значениях полей ввода дат "с" и "по":

с: 01.01.1900  по: 30.12.2090
с: 02.01.1900  по: 30.12.2090   
с: 30.01.1900  по: 30.12.2090
с: 01.01.1900  по: 01.12.2090  
с: 10.07.2000 по: 10.07.2000
с 28.05.2020 по 29.05.2020
с 28.05.2020 по 28.06.2020
с 28.05.2020 по 28.05.2021

с: 20.02.2020 по 29.02.2020
с: 29.02.2020 по 01.03.2020

Соообщение "Ошибка" при следующих значениях полей ввода дат "с" и "по":

с: 31.12.1899  по: 30.12.2090
с: 31.12.1899  по: 29.12.2090
с: 31.12.1899  по: 01.01.2091
с: 01.01.1900  по: 01.01.2091
с: 02.01.1900  по: 01.01.2091
с: 21.07.2000 по: 20.07.2000
с: 00.07.2000 по: 21.07.2000
с: 21.00.2000 по: 21.07.2000
с: 21.07.2000 по: 00.07.2000
с: 21.07.2000 по: 21.00.2000
с: 99.07.2000 по: 21.07.2000
с: 21.99.2000 по: 21.07.2000
с: 21.07.2000 по: 99.07.2000
с: 21.07.2000 по: 21.99.2000
с: 00.00.2000 по: 21.07.2000
с: 88.88.2000 по: 21.07.2000
с: 99.99.2000 по: 21.07.2000
с: 21.07.2000 по: 00.00.2000
с: 21.07.2000 по: 99.99.2000

**Comment by VladislavIlyuschits** [comment]
> Недостаточно как позитивных, так и негативных тестов.
> При проектировании позитивных тестов рекомендую отдельно проверять поля "с" и "по" на граничные значения, иначе в рамках одного теста проверяется сразу 3 условия: граничное значение "с", граничное значение "по" и минимально допустимый диапазон. В случае, если минимально допустимый диапазон задан неверно, большая часть тестов будет невалидна.

**Comment by vliplianina** [comment]
Позитивные тесты упускают технику аланиза граничных значений:
1. упущены проверки некоторых граничных значений для даты "с" и даты "по" (с = max, по = min, по = max)
2. упущены проверки некоторых граничных значений для "ДД" (ДД = max для месяцев с 28, 30, 31 днями)

Негативные тесты упускают технику аланиза граничных значений:
1. упущены проверки некоторых граничных значений для "ДД"  (ДД = max + 1 для месяцев с 28, 29, 30, 31 днями)
2. упущена проверка нижней границы негативного класса для "ММ" (ММ = max + 1)

**Comment by VladislavIlyuschits** [comment]
Соообщение "Сохранено" при следующих значениях полей ввода дат "с" и "по":

1. 
from **30.12.2090** to **30.12.2090**
from 29.12.2090 to **30.12.2090**
from **01.01.1900** to **01.01.1900**

2. 
from **28**.02.2021 to 01.03.2021
from **30**.04.2020 to 01.05.2020
from **31**.01.2020 to 01.02.2020

from 27.02.2021 to **28**.02.2021
from  29.04.2020 to **30**.04.2020
from  30.01.2020 to **31**.01.2020


Соообщение "Ошибка" при следующих значениях полей ввода дат "с" и "по":

1.
from **29**.02.2021 to 01.03.2021
from **30**.02.2020 to 01.03.2020
from **31**.04.2020 to 01.05.2020
from **32**.01.2020 to 01.02.2020

from 28.02.2021 to **29**.02.2021
from 29.02.2020 to **30**.02.2020
from 30.04.2020 to **31**.04.2020
from 31.01.2020 to **32**.01.2020

2.
from 20.**13**.2020 to 01.01.2021
from 20.12.2020 to 01.**13**.2020

**Comment by vliplianina** [comment]
Принято
